// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace dotnet_NewProject.Migrations.homepromo
{
    [DbContext(typeof(homepromoContext))]
    [Migration("20211018140623_Update20211018-2105")]
    partial class Update202110182105
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("dotnet_NewProject.Models.modelHomePromo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DurationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DurationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromoType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Store")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("modelHomePromo");
                });
#pragma warning restore 612, 618
        }
    }
}
